workflows:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

configs:
  - changed-files:
      - any-glob-to-any-file: .github/*.yml

scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**

templates:
  - changed-files:
      - any-glob-to-any-file: templates/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**
