---
name: 🏷️ Pull Request Labeler
# Copied: https://github.com/cangulo-actions/github-workflows-templates/blob/main/templates/labeler.yml

on:
  pull_request:
    branches:
      - main

concurrency:
  group: label-PR-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  labeler:
    name: 🏷️ PR Label
    permissions:
      contents: read
      pull-requests: write
    uses: cangulo-actions/github-workflows-templates/.github/workflows/labeler.yml@main
    with:
      configuration-template: github-action
