---
name: 🔎 Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: lint-PR-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: 🔎 Lint
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    use: cangulo-actions/github-workflows-templates/.github/workflows/lint.yml@main
