---
name: 🚀 Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions: {}

jobs:
  semver:
    name: 🚀 release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: release new version
        uses: cangulo-actions/semver@main
        id: semver
        with:
          create-gh-release: true
          print-summary: true
          print-annotations: true

  lint:
    name: 🔎 Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
