---
name: 🚀 Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    name: 🚀 release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: release new version
        uses: cangulo-actions/semver@main
        id: semver
        with:
          create-gh-release: true
          print-summary: true
          print-annotations: true
          github-token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for creating the GH release
